name: Duncan Wallis
favicon: null
layout_spectrum: 0.99939
typography_spectrum: 0.73633
title: From The Outer Edge - The Photography of Duncan Wallis
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020001'
    - '#3c404b'
    - '#febab9'
    - '#906a73'
    - '#fdede2'
  brandStrength: 0.25
  lightness: 0.18241103389300406
  saturation: 0.1485799760557711
  rhythmicContrast: 1
purpose: []
